#ifndef _ESSENTIAL_H_
#define _ESSENTIAL_H_

/*
*This class is mainly for definition of statuc code, it also includes some command header file
*names.
*
*Main Author: Akshat, Kai Wen, Joan, Junchao
*/

#include <vector>
#include <string>

using namespace std;

enum STATUS_CODE_SET_OVERALL{
	OVERALL_SUCCESS,
	OVERALL_WARNING,
	OVERALL_ERROR,
	OVERALL_PROMPT,
	OVERALL_EXIT,
};

enum STATUS_CODE_SET_SUCCESS{
	SUCCESS_ADD = OVERALL_EXIT + 1,
	SUCCESS_REMOVE,
	SUCCESS_DISPLAY,
	SUCCESS_UPDATE,
	SUCCESS_RESHCEDULE,
	SUCCESS_MARK,
	SUCCESS_SEARCH,
	SUCCESS_LOAD,
	SUCCESS_SAVE,
	SUCCESS_UNDO,
	SUCCESS_REDO,
	SUCCESS_RECORD,
	SUCCESS_INTERPRET_ADD,
	SUCCESS_INTERPRET_REMOVE,
	SUCCESS_INTERPRET_DISPLAY,
	SUCCESS_INTERPRET_RENAME,
	SUCCESS_INTERPRET_RESCHEDULE,	
	SUCCESS_INTERPRET_MARK,
	SUCCESS_INTERPRET_SEARCH,
	SUCCESS_INTERPRET_STRINGTODATETIME
};

enum STATUS_CODE_SET_WARNING{
	WARNING_ADD_CLASH = SUCCESS_INTERPRET_STRINGTODATETIME + 1,	
	WARNING_ADD_DUPLICATE,
	WARNING_DISPLAY_NO_RESULT,
	WARNING_UPDATE_SAME,	
	WARNING_UPDATE_CLASH,
	WARNING_MARK_NO_CHANGE,
	WARNING_SEARCH_NO_RESULT,
	WARNING_UNDO_NO_TASKS,
	WARNING_REDO_NO_TASKS,
	WARNING_LOAD_EMPTY_FILE,	
	WARNING_INTERPRET_ADD_NO_TITLE,
	WARNING_WRONG_INPUT,
};

enum STATUS_CODE_SET_ERROR{
	ERROR_ADD = WARNING_WRONG_INPUT + 1,
	ERROR_REMOVE,
	ERROR_DISPLAY,
	ERROR_UPDATE,
	ERROR_MARK,
	ERROR_SEARCH,
	ERROR_UNDO,
	ERROR_REDO,
	ERROR_LOAD_OPENFILE,
	ERROR_LOAD_CORRUPTED_DATA,
	ERROR_SAVE_SAVEFILE,
	ERROR_RECORD,
	ERROR_INVALID_CHOICE,
	ERROR_INTERPRET_EMPTY_INPUT,
	ERROR_INTERPRET_TITLE_FORMAT,
	ERROR_INTERPRET_DATETIME_FORMAT,
	ERROR_INTERPRET_MISSING_KEYWORD,
	ERROR_INTERPRET_ADD,
	ERROR_INTERPRET_REMOVE,
	ERROR_INTERPRET_DISPLAY,
	ERROR_INTERPRET_RENAME,	
	ERROR_INTERPRET_RESCHEDULE,
	ERROR_INTERPRET_MARK,
	ERROR_INTERPRET_SEARCH,
	ERROR_INTERPRET_STRINGTODATETIME
};

enum STATUS_CODE_SET_PROPMT{
	PROMPT_REMOVE_CHOOSE = ERROR_INTERPRET_STRINGTODATETIME+1,
	PROMPT_RENAME_CHOOSE,
	PROMPT_RESCHEDULE_CHOOSE,
	PROMPT_MARK_CHOOSE,
};

#endif
